# version: '3'

# services:
#   db:
#     image: postgres:14.3
#     restart: always
#     ports: 
#       - "5432:5432"
#     environment:
#       POSTGRES_USERNAME: postgres
#       POSTGRES_PASSWORD: asesoresApp
#       POSTGRES_DB: asesoresApp
#     container_name: AsesoresApp
#     volumes:
#       - ./postgres:/var/lib/postgresql/data

version: '3.8'

services:
  app:
    image: nestjs-docker:local
    container_name: nestjs-docker
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - .:/app